---
apiVersion: v1
kind: Service
metadata:
    name: rabbitmq-service
spec:
    selector:
        app: taskQueue
    ports:
        - protocol: TCP
          name: rabbitmq-port
          port: 5672
          targetPort: 5672
          nodePort: 30003
        - protocol: TCP
          name: rabbitmq-ui
          targetPort: 15672
          port: 15672
          nodePort: 30004
    type: NodePort
---
apiVersion: v1
kind: ReplicationController
metadata:
    name: rabbitmq-controller
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: taskQueue
        spec:
            containers:
                - name: rabbitmq
                  image: rabbitmq:management
                  ports:
                      - containerPort: 5672
                  env:
                      - name: RABBITMQ_DEFAULT_USER
                        value: 'user'
                      - name: RABBITMQ_DEFAULT_PASS
                        value: 'pass'
                      - name: RABBITMQ_HOST
                        value: 'rabbitmq-service'
