---
kind: Service
apiVersion: v1
metadata:
    name: auth-service
spec:
    selector:
        app: auth
    ports:
        - protocol: 'TCP'
          port: 4002
          targetPort: 4001
          nodePort: 30002
    type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: auth-deployment
spec:
    replicas: 2
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
                - name: auth
                  image: 49514951/auth:test
                  ports:
                      - containerPort: 4001
                  env:
                      - name: RABBITMQ_DEFAULT_USER
                        value: 'user'
                      - name: RABBITMQ_DEFAULT_PASS
                        value: 'pass'
                      - name: RABBITMQ_HOST
                        value: 'rabbitmq-service'
