---
kind: Service
apiVersion: v1
metadata:
    name: gateway-service
spec:
    selector:
        app: gateway
    ports:
        - protocol: 'TCP'
          port: 4001
          targetPort: 4000
          nodePort: 30001
    type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: gateway-deployment
spec:
    replicas: 2
    template:
        metadata:
            labels:
                app: gateway
        spec:
            containers:
                - name: gateway
                  image: 49514951/gateway:test
                  ports:
                      - containerPort: 4000
